# Generated by Django 2.2.15 on 2020-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20201025_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name_plural': 'Achievement'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name_plural': 'Expertise'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaskedquestions',
            options={'verbose_name_plural': 'FrequentlyAskedQuestions'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Testimonial'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name_plural': 'Values'},
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
