# Generated by Django 2.2.15 on 2020-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
