# Generated by Django 2.2.15 on 2020-10-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20201025_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='main_content',
        ),
    ]
