# Generated by Django 2.2.15 on 2021-01-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20210105_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Team'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='title',
        ),
    ]
