# Generated by Django 2.2.15 on 2021-01-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
